name: AndroidBuild

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - feature-AI-Image-Recogniser
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v4.2.2

      - name: Write google-services.json from GitHub Secrets
        run: echo "SERVICE_JSON" > app/google-services.json
        env:
          SERVICE_JSON: ${{ secrets.SERVICE_JSON }}

      - name: Set execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin' # You can also use 'zulu', 'adopt', etc.
          java-version: '17.0.2+8'

      - name: Build with Gradle
        run : ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: CICD.apk
          path: app/build/outputs/apk/debug/app-debug.apk



